# Generated by Django 5.2.4 on 2025-07-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Country name')),
                ('code', models.CharField(max_length=5, verbose_name='Country code')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', verbose_name='File')),
                ('type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('music', 'Music'), ('video', 'Video')], max_length=60, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Customer name')),
                ('customer_position', models.CharField(max_length=120, verbose_name='Customer position')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedback', to='common.media')),
            ],
        ),
        migrations.CreateModel(
            name='OurInstagramStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_instagram_story', to='common.media')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Region name')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='common.country')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=120, verbose_name='Home title')),
                ('home_subtitle', models.TextField(max_length=1500, verbose_name='Home subtitle')),
                ('home_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
        ),
    ]
