# Generated by Django 5.2.4 on 2025-07-31 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_country_options_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinstagramstory',
            name='link',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['https://instagram.com', 'https://www.instagram.com'])], verbose_name='Link'),
        ),
    ]
