# Generated by Django 5.2.4 on 2025-07-31 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_ourinstagramstory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinstagramstory',
            name='link',
            field=models.URLField(validators=[django.core.validators.RegexValidator(message='Please enter a valid Instagram URL.', regex='^https?://(www\\.)?instagram\\.com/.*$')], verbose_name='Link'),
        ),
    ]
