# Generated by Django 5.2.4 on 2025-07-31 05:07

import accounts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress_verificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,12}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,12}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pin_code',
            field=models.CharField(max_length=60, verbose_name='Pin code'),
        ),
        migrations.AlterField(
            model_name='verificationotp',
            name='code',
            field=models.IntegerField(validators=[accounts.utils.CheckVerifacationOtp], verbose_name='Otp code'),
        ),
    ]
