# Generated by Django 5.2.4 on 2025-08-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_address_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationotp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
